# Generated by Django 4.2.21 on 2025-06-10 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scp4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อโปรเจกต์')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบายโปรเจกต์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดตล่าสุด')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'โปรเจกต์',
                'verbose_name_plural': 'โปรเจกต์',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่และเวลาที่สแกน')),
                ('scan_duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='ระยะเวลาสแกน (วินาที)')),
                ('ollama_model_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='เวอร์ชัน Ollama Model')),
                ('total_vulnerabilities', models.IntegerField(default=0, verbose_name='จำนวนช่องโหว่รวม')),
                ('high_severity_count', models.IntegerField(default=0, verbose_name='จำนวนช่องโหว่ความรุนแรงสูง')),
                ('medium_severity_count', models.IntegerField(default=0, verbose_name='จำนวนช่องโหว่ความรุนแรงปานกลาง')),
                ('low_severity_count', models.IntegerField(default=0, verbose_name='จำนวนช่องโหว่ความรุนแรงต่ำ')),
                ('info_severity_count', models.IntegerField(default=0, verbose_name='จำนวนช่องโหว่ข้อมูล')),
                ('scanned_code', models.TextField(blank=True, null=True, verbose_name='โค้ดที่ถูกสแกน')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='scp4.project', verbose_name='โปรเจกต์')),
            ],
            options={
                'verbose_name': 'ผลลัพธ์การสแกน',
                'verbose_name_plural': 'ผลลัพธ์การสแกน',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'ผลลัพธ์ดิบจากการวิเคราะห์ (Legacy)', 'verbose_name_plural': 'ผลลัพธ์ดิบจากการวิเคราะห์ (Legacy)'},
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='raw_analysis_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='code',
            field=models.TextField(verbose_name='โค้ดที่วิเคราะห์'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่วิเคราะห์'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='result',
            field=models.TextField(verbose_name='ผลลัพธ์ดิบจาก AI'),
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อช่องโหว่')),
                ('description', models.TextField(verbose_name='คำอธิบายช่องโหว่')),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info')], max_length=20, verbose_name='ระดับความรุนแรง')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='ไฟล์ที่พบ')),
                ('line_number', models.IntegerField(blank=True, null=True, verbose_name='บรรทัดที่พบ')),
                ('code_snippet', models.TextField(blank=True, null=True, verbose_name='ส่วนของโค้ดที่เกี่ยวข้อง')),
                ('remediation_advice', models.TextField(blank=True, null=True, verbose_name='คำแนะนำในการแก้ไข')),
                ('owasp_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='ลิงก์ OWASP/ข้อมูลเพิ่มเติม')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Fixed', 'Fixed'), ('False Positive', 'False Positive'), ('Accepted Risk', 'Accepted Risk')], default='Open', max_length=20, verbose_name='สถานะ')),
                ('raw_ai_output', models.JSONField(blank=True, null=True, verbose_name='ผลลัพธ์ดิบจาก AI')),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scp4.scanresult', verbose_name='ผลลัพธ์การสแกน')),
            ],
            options={
                'verbose_name': 'ช่องโหว่',
                'verbose_name_plural': 'ช่องโหว่',
            },
        ),
    ]
