# Generated by Django 4.2.21 on 2025-07-19 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scp4', '0003_alter_vulnerability_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='project',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
