# Generated by Django 4.2.21 on 2025-09-10 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scp4', '0005_useractivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='รับการแจ้งเตือนทางอีเมล')),
                ('preferred_language', models.CharField(choices=[('th', 'ไทย'), ('en', 'English')], default='th', max_length=10, verbose_name='ภาษาที่ต้องการ')),
                ('total_scans_count', models.PositiveIntegerField(default=0, verbose_name='จำนวนการสแกนทั้งหมด')),
                ('last_scan_date', models.DateTimeField(blank=True, null=True, verbose_name='การสแกนล่าสุด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'โปรไฟล์ผู้ใช้',
                'verbose_name_plural': 'โปรไฟล์ผู้ใช้',
            },
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='vulnerability',
            options={'ordering': [models.Case(models.When(severity='Critical', then=models.Value(1)), models.When(severity='High', then=models.Value(2)), models.When(severity='Medium', then=models.Value(3)), models.When(severity='Low', then=models.Value(4)), models.When(severity='Informational', then=models.Value(5)), default=models.Value(6), output_field=models.IntegerField()), 'name'], 'verbose_name': 'ช่องโหว่', 'verbose_name_plural': 'ช่องโหว่'},
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='ollama_model_version',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='scan_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='line_number',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='owasp_link',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='status',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='ai_model_used',
            field=models.CharField(default='deepseek-coder:6.7b', max_length=100, verbose_name='AI Model ที่ใช้'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='attack_scenario',
            field=models.TextField(blank=True, null=True, verbose_name='สถานการณ์การโจมตี'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cwe_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CWE ID'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='analysis_result_raw',
            field=models.TextField(blank=True, null=True, verbose_name='ผลลัพธ์ดิบจาก AI'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='critical_severity_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Critical'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='high_severity_count',
            field=models.PositiveIntegerField(default=0, verbose_name='High'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='info_severity_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='low_severity_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Low'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='medium_severity_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Medium'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='วันที่และเวลาที่สแกน'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='total_vulnerabilities',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนช่องโหว่รวม'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='code_snippet',
            field=models.TextField(blank=True, null=True, verbose_name='โค้ดที่เกี่ยวข้อง'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='description',
            field=models.TextField(verbose_name='คำอธิบาย'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='remediation',
            field=models.TextField(blank=True, null=True, verbose_name='วิธีแก้ไข'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Informational', 'Informational')], db_index=True, max_length=20, verbose_name='ระดับความรุนแรง'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['user', '-scanned_at'], name='scp4_scanre_user_id_959136_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['total_vulnerabilities'], name='scp4_scanre_total_v_d9e582_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['scanned_at'], name='scp4_scanre_scanned_7d85dc_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['scan_result', 'severity'], name='scp4_vulner_scan_re_fb9223_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['severity'], name='scp4_vulner_severit_b52a4c_idx'),
        ),
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
