# Generated by Django 4.2.21 on 2025-10-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp4', '0006_userprofile_remove_analysisresult_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='knowledge_base_count',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนข้อมูลจาก Knowledge Base ที่ใช้'),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='rag_context_used',
            field=models.TextField(blank=True, help_text='บันทึกว่าใช้ข้อมูลจาก Knowledge Base อะไรบ้าง', null=True, verbose_name='ข้อมูล RAG ที่ใช้'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='ai_model_used',
            field=models.CharField(default='codellama:7b', max_length=100, verbose_name='AI Model ที่ใช้'),
        ),
        migrations.CreateModel(
            name='VulnerabilityKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='เช่น SQL Injection, XSS, CSRF', max_length=255, unique=True, verbose_name='ชื่อช่องโหว่')),
                ('cwe_id', models.CharField(blank=True, help_text='เช่น CWE-89, CWE-79', max_length=20, null=True, verbose_name='CWE ID')),
                ('owasp_category', models.CharField(blank=True, help_text='เช่น A03:2021 - Injection', max_length=100, null=True, verbose_name='OWASP Category')),
                ('description', models.TextField(help_text='อธิบายว่าช่องโหว่นี้คืออะไร เกิดจากอะไร', verbose_name='คำอธิบายช่องโหว่')),
                ('impact', models.TextField(help_text='อธิบายว่าถ้าถูกโจมตีจะเกิดอะไรขึ้น', verbose_name='ผลกระทบ')),
                ('remediation', models.TextField(help_text='แนะนำวิธีป้องกันและแก้ไข', verbose_name='วิธีแก้ไข')),
                ('vulnerable_code_example', models.TextField(blank=True, null=True, verbose_name='ตัวอย่างโค้ดที่มีช่องโหว่')),
                ('secure_code_example', models.TextField(blank=True, null=True, verbose_name='ตัวอย่างโค้ดที่ปลอดภัย')),
                ('keywords', models.TextField(blank=True, help_text='คำสำคัญแยกด้วยเครื่องหมายจุลภาค เช่น sql,query,database,injection', null=True, verbose_name='คำสำคัญ')),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Informational', 'Informational')], default='Medium', max_length=20, verbose_name='ระดับความรุนแรงทั่วไป')),
                ('reference_url', models.URLField(blank=True, null=True, verbose_name='URL อ้างอิง')),
                ('is_active', models.BooleanField(default=True, help_text='เปิด/ปิดการใช้งานในระบบ RAG', verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ฐานความรู้ช่องโหว่',
                'verbose_name_plural': 'ฐานความรู้ช่องโหว่',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='scp4_vulner_name_a621ab_idx'), models.Index(fields=['cwe_id'], name='scp4_vulner_cwe_id_0e9dfc_idx'), models.Index(fields=['is_active'], name='scp4_vulner_is_acti_d9cb63_idx')],
            },
        ),
    ]
